export const Classic = {
    colors: {
        background: '#E4ECEA',
        backgroundModal: '#26465366',
        backgroundSecondary: '#FFFFFF',
        lightIcon: '#FFFFFF',
        darkIcon: '#E4ECEA',
        text: '#0D0E0E',
        altText: '#264653',
        primary: '#264653',
        loading: '#DFE17B',
        accent: '#D1406C',
        border: '#A49DAA',
        linePrimary: '#00B0FF',
        borderLinePrimary: '#1c68d1',
        lineSecondary: '#bbbdbf',
        borderLineSecondary: '#8c8f91',
        active: '#78DBC8',
        stats: '#207665',
        empty: '#EFF0F1',
        filled: '#2A9D87',
        ligthLine: '#E4E4EA',
        easy: '#22C55E',
        medium: '#F59E0B',
        hard: '#EF4444',
    },
};

export const Dark = {
    colors: {
        background: '#0D0E0E',
        backgroundModal: '#26465366',
        backgroundSecondary: '#1F2937',
        lightIcon: '#E4E4EA',
        darkIcon: '#E4ECEA',
        text: '#FFFFFF',
        altText: '#FFFFFF',
        primary: '#264653',
        loading: '#DFE17B',
        accent: '#D1406C',
        border: '#A49DAA',
        linePrimary: '#00B0FF',
        borderLinePrimary: '#1c68d1',
        lineSecondary: '#bbbdbf',
        borderLineSecondary: '#8c8f91',
        active: '#78DBC8',
        stats: '#207665',
        empty: '#EFF0F1',
        filled: '#2A9D87',
        ligthLine: '#E4E4EA',
        easy: '#22C55E',
        medium: '#F59E0B',
        hard: '#EF4444',
    },
};
