import { DefaultTheme } from '@react-navigation/native';

export const Classic = {
    ...DefaultTheme,
    colors: {
        ...DefaultTheme.colors,
        background: '#E4ECEA',
        backgroundmodal: '#26465366',
        backgroundsecondary: '#FFFFFF',
        text: '#0D0E0E',
        link: '#264653',
        primary: '#DFE17B',
        secondary: '#80C8D2',
        accent: '#D1406C',
        border: '#A49DAA',
        accentuated: '#1D343E',
        lineprimary: '#00B0FF',
        borderlineprimary: '#1c68d1',
        linesecondary: '#bbbdbf',
        borderlinesecondary: '#8c8f91',
        iconprimary: '#78DBC8',
        label: '#F2F7F9',
        stats: '#207665',
        statstext: '#0D0E0E',
        description: '#6B6F70',
        starEmpty: '#EFF0F1',
        starFill: '#2A9D87',
    },
};

export const Dark = {
    ...DefaultTheme,
    colors: {
        ...DefaultTheme.colors,
        background: '#E4ECEA',
        backgroundsecondary: '#26465366',
        backgroundTextInput: '#FFFFFF',
        text: '#0D0E0E',
        link: '#264653',
        primary: '#DFE17B',
        secondary: '#80C8D2',
        accent: '#D1406C',
        border: '#A49DAA',
        accentuated: '#1D343E',
        lineprimary: '#00B0FF',
        borderlineprimary: '#1c68d1',
        linesecondary: '#bbbdbf',
        borderlinesecondary: '#8c8f91',
        iconprimary: '#78DBC8',
        label: '#F2F7F9',
        stats: '#207665',
        statstext: '#0D0E0E',
        description: '#6B6F70',
        starEmpty: '#EFF0F1',
        starFill: '#2A9D87',
        styleBar: '#E1E2E3',
    },
};
